### PR TITLE
Merging all BREI omni nav updates into chapmanu's repo

### PR DESCRIPTION
**Pull request by sharissis-brei**
Note: I changed the file structure inside of the src folder a bit.

1. I've added subfolders for the JS and Sass for organizational purposes.
2. I've added a level version of both index.html (index-level.html) and omni-nav.html (omni-nav-level.html). These files account for the version of the off canvas nav that have 2 levels (whereas pages not in a bucket category only have one level).

Let me know if you have any questions.

### CODE REVIEW

**Comment by homeofmatt** [comment]
@sharissis-brei, can you update the index.html and the index-level.html to reflect your file structure changes? Otherwise, I tested everything out by merging your changes into a separate branch here in our folder and it all looks great!

**Comment by sharissis-brei** [comment]
Hi Matt, I apologize for the delay getting back to you.

I'm not sure I understand what you are asking for here. If you are wondering why there are two versions of each file, one is the pre-compiled version (in /src) and the other is the compiled version (in the root directory).

Let me know what you'd like me to do from here, thanks.

**Comment by homeofmatt** [comment]
I'm talking about the changes to the folder structure: "I've added subfolders for the JS and Sass for organizational purposes."

It's really minor. I'm just talking about a README update across all of the files that include instructions to modify files based off of the old file structure (README.md, index.html, & index-level.html)

**Comment by homeofmatt** [comment]
Awesome, I'm gonna go ahead and merge :+1:

**Pull request merged**
