### PR TITLE
Merged updates; Updated styles

### PR DESCRIPTION
**Pull request by Sean-BREI**
- Removed .the-university CSS class

Note: We cannot merge updates into your repo. We don't have access rights here at BarkleyREI.

### CODE REVIEW

**Comment by homeofmatt** [comment]
Bummer, I thought you guys might have.

**Comment by homeofmatt** [comment]
@Sean-BREI how are you guys going about compiling the omni-nav css and js files for cascade? With the instructions on this repo or do you guys have your own method?
I just want to make sure the asset files I deploy to our other sites (events, social, inside, blogs) will be identical to the asset files on cascade.

**Comment by Sean-BREI** [comment]
@homeofmatt Same instructions regarding what's described on the repo. I just run "grunt" in the command line to compile the files.

**Comment by homeofmatt** [comment]
good to hear, thanks!

**Pull request merged**
