### PR TITLE
Various Omni-Nav CSS/Style Updates

### PR DESCRIPTION
**Pull request by Sean-BREI**
Please review the following changes. The final was requested could also not be made presently. I will need additional details: ..."could the margin on the logo, the X, and the Main Menu text be aligned with the icons?"

1. #313131 changed to #444444 for Main link in Omni Nav menu
2. Submenu link color changed to #676767
3. Submenu link background color changed to #f5f5f5
4. An active state was applied to the Main menu link using Chapman U.’s
color red for branding - #a82439 (#a8s439 was used instead of #98002E
due to a left comment in the SASS stylesheet regarding color standards)
5. An :active state was applied to the submenu links using Chapman U.’s
color red for branding - #a82439

### CODE REVIEW

**Comment by waidelacruz** [comment]
@Sean-BREI Regarding margins, pls see the comp attached. Thanks!
cu-omninav

**Comment by homeofmatt** [comment]
@Sean-BREI, I updated the '$cu-red' css variable to be using the new red ( #98002E ). Just pull the commits your fork is missing from ours when you can. Thanks!

**Comment by waidelacruz** [comment]
Re: _An :active state was applied to the submenu links using Chapman U.’s color red for branding - #a82439_ >> @Sean-BREI  I noticed the submenu still appears blue, but Matt mentioned yesterday you guys might still be in the middle of making changes. Thought I'd bring this to your attention. Thanks Sean!

**Comment by Sean-BREI** [comment]
@waidelacruz No, were not making changes at this time. The :active state does work, though, when you click and hold down on a link.

**Comment by waidelacruz** [comment]
@Sean-BREI Oh yes, sorry about that. I meant for the submenu to be :hover state as illustrated in the comp. Thanks again!

**Comment by Sean-BREI** [comment]
@waidelacruz Just to clarify, the :hover state should also be Chapman U.'s red - #a82439 too? I can also make that change if you like?

**Comment by waidelacruz** [comment]
@Sean-BREI The new Chapman Red is #98002e. I believe Matt already changed its variable? The new :active state is #7f0026. Thanks so much!

**Comment by homeofmatt** [comment]
@Sean-BREI I just saw what you meant about using the old red due to the comment in the stylesheet. Looks like we used to use #98002E, but I guess we're using it again but across the board this time. Thanks for bringing that up though, good eye

**Comment by Sean-BREI** [comment]
@waidelacruz I created a Pull Request regarding the aforementioned updates. Please review and merge assets. I'll leave the Production CMS updates and publishing to you unless specified otherwise. I don't wan't to update any files without your permission. However, Dev has been updated with the new stylesheet.

**Pull request merged**
